output "cluster_id" {
  value = module.eks.cluster_id
}

output "cluster_security_groups" {
  value = [
    module.eks.cluster_security_group_id,
    module.eks.worker_security_group_id
  ]
}

output "cluster_oidc_provider_url" {
  value = module.eks.cluster_oidc_issuer_url
}

output "kubernetes_cluster_endpoint" {
  description = "Endpoint for EKS control plane."
  value       = module.eks.cluster_endpoint
}

output "kubernetes_cluster_security_group_id" {
  description = "Security group ids attached to the cluster control plane."
  value       = module.eks.cluster_security_group_id
}

output "kubernetes_kubectl_config" {
  description = "kubectl config as generated by the module."
  value       = module.eks.kubeconfig
}

output "irsa_role_admin_arn" {
  value = module.iam_assumable_role_admin.this_iam_role_arn
}

output "irsa_loadbalancer_serviceaccount_specs" {
  value = {
    name      = local.k8s_service_account_name
    namespace = local.k8s_service_account_namespace
  }
}
